version: 2.1

executors:
  node-step:
    docker:
      - image: cimg/node:22.4.1

jobs:
  deps-install:
    executor: node-step
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn3-node18-{{ checksum "yarn.lock" }}
            - yarn3-node18
          paths:
            - ~/project/.yarn/cache
      - run:
          command: yarn install --immutable
      - save_cache:
          key: yarn3-node18-{ checksum "yarn.lock" }}
          paths:
            - ~/project/.yarn/cache
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - .yarn/cache

  code-lint:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint

  commit-lint:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint:commit:ci

  build:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  publish:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn release

workflows:
  version: 2
  build:
    jobs:
      - deps-install
      - build:
          requires:
            - deps-install
      - code-lint:
          requires:
            - deps-install
            - build
      - commit-lint:
          requires:
            - deps-install
      - publish:
          context: semver
          filters:
            branches:
              only:
                - master
          requires:
            - code-lint
            - commit-lint
            - build
