version: 2.1

executors:
  node-step:
    docker:
      - image: circleci/node:16.13.1

jobs:
  deps-install:
    executor: node-step
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-install-node16-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - yarn-install-node16-{{ checksum "package.json" }}
            - yarn-install-node16
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-install-node16-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  code-lint:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint

  commit-lint:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn lint:commit:ci

  build:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build

  publish:
    executor: node-step
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: yarn release

workflows:
  version: 2
  build:
    jobs:
      - deps-install
      - build:
          requires:
            - deps-install
      - code-lint:
          requires:
            - deps-install
            - build
      - commit-lint:
          requires:
            - deps-install
      - publish:
          context: semver
          filters:
            branches:
              only:
                - master
          requires:
            - code-lint
            - commit-lint
            - build
